export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//Donor & Store
export const ALL_APPOINTMENT_LOG_SUCCESS = 'ALL_APPOINTMENT_LOG_SUCCESS';
export const ALL_APPOINTMENT_LOG_FAIL = 'ALL_APPOINTMENT_LOG_FAIL';

export const APPOINTMENT_SLOTS_SUCCESS = 'APPOINTMENT_SLOTS_SUCCESS';
export const APPOINTMENT_SLOTS_FAIL = 'APPOINTMENT_SLOTS_FAIL';



export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';


// Store Container Page Types:
export const FETCH_ALL_AVAILABLE_BLOOD_SUCCESS = 'FETCH_ALL_AVAILABLE_BLOOD_SUCCESS';
export const FETCH_ALL_AVAILABLE_BLOOD_FAIL = 'FETCH_ALL_AVAILABLE_BLOOD_FAIL';

//  Store Admin Request:
export const SAVE_ADMIN_REQUEST_SUCCESS = 'SAVE_ADMIN_REQUEST_SUCCESS';
export const SAVE_ADMIN_REQUEST_FAIL = 'SAVE_ADMIN_REQUEST_FAIL'

//  Store Fetch All Donar Data:
export const FETCH_ALL_DONOR_DATA_SUCCESS = 'FETCH_ALL_DONOR_DATA_SUCCESS';
export const FETCH_ALL_DONOR_DATA_FAIL = 'FETCH_ALL_DONOR_DATA_FAIL';

//  donor Fetch My Requests
export const FETCH_ALL_MY_REQUESTS_SUCCESS = 'FETCH_ALL_MY_REQUESTS_SUCCESS';
export const FETCH_ALL_MY_REQUESTS_FAIL = 'FETCH_ALL_MY_REQUESTS_FAIL';

//  donor Edit My Request
export const EDIT_MY_REQUEST_SUCCESS = 'EDIT_MY_REQUEST_SUCCESS'
export const EDIT_MY_REQUEST_FAIL = 'EDIT_MY_REQUEST_FAIL'